### ISSUE TITLE
Move URL Input box underneath file import and folder mounting

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/texture-tool#5]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/30747200/177159721-9138ed41-2d66-4c9b-b40e-4672bc81fa2a.png">

Figma link: https://www.figma.com/file/tgjz0PLgrPoJ9gh6nqkNGw/PlayCanvas-Texture-Viewer?node-id=5%3A7

**Comment by slimbuck** [comment]
fixed in #10
