### ISSUE TITLE
Update logo to the most up to date version with a gradient

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/texture-tool#6]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/30747200/177159875-3acdf4f6-5209-412e-9b28-a1bdbacdc881.png">

Also, change copy from "local files" to "Texture Viewer"

Logo can be downloaded here:https://drive.google.com/file/d/1Xiqhm4GSm-wr2-AKcRreOVPJWr0kXrNJ/view?usp=sharing

**Comment by slimbuck** [comment]
fixed in #10
