### ISSUE TITLE
Export to png UI changes

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/texture-tool#7]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/30747200/177160331-8a44c1e1-a14a-4351-b961-58cfc69cc5af.png">

1. Move the drawer right below reproject drawer 
2. Add icon to the button to add more visual hierarchy to the UI

Figma link:https://www.figma.com/file/tgjz0PLgrPoJ9gh6nqkNGw/PlayCanvas-Texture-Viewer?node-id=14%3A535

**Comment by slimbuck** [comment]
fixed in #10
