### ISSUE TITLE
Add feedback channel to side panel 

### ISSUE THREAD

**Issue by jiajasper** [playcanvas/texture-tool#9]
Add github link and feedback forum link to the tool for feedback collection.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/30747200/177179911-08b9b9b2-4ef0-490f-ac5c-5c4059055097.png">

Figma link: https://www.figma.com/file/tgjz0PLgrPoJ9gh6nqkNGw/PlayCanvas-Texture-Viewer?node-id=14%3A535

**Comment by slimbuck** [comment]
fixed in #10
